/**
 * `/manifesto` — what this thing believes, in the order the beliefs matter.
 *
 * Not a feature list with adjectives. Every section names a decision that was
 * actually made in the code and could have gone the other way, and says what it
 * costs. A reader who disagrees with one of these should be able to tell
 * immediately, which is the only thing a document like this is for.
 */
import { Link } from 'react-router-dom'

import { DOCS_URL, REPO_URL, SiteShell } from '@/pages/siteShared'

const BELIEFS: Array<{ title: string; body: string }> = [
  {
    title: 'The agent is a surface, not a feature',
    body: 'Most products bolted a chat box onto a sidebar and called it AI. Here the tool layer came first and every surface dispatches through it: the in-app agent, Slack, the hosted MCP server your ChatGPT or Claude connects to, and a CLI a coding agent can drive. One brain, four doors, the same organization-scoped permissions. A capability that exists in the UI and not in the tool layer is a bug.',
  },
  {
    title: 'Anything irreversible stops at a human',
    body: 'The agent reads freely and writes nothing sensitive without an inline Approve or Deny — sending email, deciding a submission, publishing, deleting. This is deliberately slower than autonomy. An agent that can quietly email 200 speakers is not a productivity feature, it is a liability with good branding.',
  },
  {
    title: 'Your program data is yours, in the shape you gave it',
    body: 'Public schedule, speaker gallery, embeds, iCal, read-only JSON, a stable REST API, CSV in and out, and a ZIP of every collected file. No export ticket, no CSV that loses your custom fields. The test of an open system is whether leaving it is boring.',
  },
  {
    title: 'Review is a conversation with a paper trail',
    body: 'Scores, comments and abstentions live on one shared page per submission, attributed, inside rounds you can open and close. Blind review is a setting, not a different product. And nothing is quietly overwritten: content keeps its versions, session edits keep their revisions with attribution, and a decision can be walked back.',
  },
  {
    title: 'The speaker is a user, not a record',
    body: 'One page to submit, no account until there is something to protect, a draft that survives a closed tab, and a manage link that works without waiting for an email. Then one portal with one checklist. Every hour you save your speakers is an hour your program team does not spend chasing them.',
  },
  {
    title: 'Configuration is data, and it is readable',
    body: 'Forms, conditional logic, rubrics and rules are documents rather than a box-and-wire builder — which means they can be reviewed, diffed, generated by an assistant, and moved between events. The rule engine ships twice, in Python and TypeScript, against shared fixtures, so the live preview and the server can never disagree.',
  },
  {
    title: 'Claims should be checkable',
    body: 'This one is open source under MIT, including the seeder that builds the demo workspace anyone can open as an organizer, a reviewer or a speaker. It was graded 100/100 by an independent evaluation harness driving the same deployment you can open right now. Every sentence on this site should be something you can go and verify, or it should not be here.',
  },
]

export function Manifesto() {
  return (
    <SiteShell badge="Manifesto">
      <section className="wrap sect">
        <div className="rv in" style={{ maxWidth: '62ch' }}>
          <p className="eyebrow">What this believes</p>
          <h1 className="h1 serif">Conference software should be operable by whoever shows up.</h1>
          <p className="lede">
            A program team, a reviewer with forty minutes on a Sunday, a speaker on a phone, and
            increasingly an agent working on someone&rsquo;s behalf. Seven decisions follow from
            that, and each one could have gone the other way.
          </p>
        </div>

        <ol className="beliefs" style={{ marginTop: 44 }}>
          {BELIEFS.map(({ title, body }, index) => (
            <li key={title} className="rv" style={{ ['--d' as string]: `${index * 0.04}s` }}>
              <em aria-hidden="true">{String(index + 1).padStart(2, '0')}</em>
              <div>
                <h2>{title}</h2>
                <p>{body}</p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section className="light">
        <div className="wrap">
          <div className="rv" style={{ maxWidth: '58ch' }}>
            <p className="eyebrow">Go and check</p>
            <h2 className="h2 serif">None of that is worth anything unverified.</h2>
            <p className="lede">
              Open the workspace as any of its three audiences, read the tool list, or read the
              source that produced both.
            </p>
            <div className="ctas" style={{ marginTop: 26 }}>
              <Link to="/judge" className="btn p">
                Open it as any role →
              </Link>
              <a href={REPO_URL} className="btn t">
                Read the source →
              </a>
              <a href={`${DOCS_URL}/ai/mcp`} className="btn t">
                Connect an agent →
              </a>
            </div>
          </div>
        </div>
      </section>
    </SiteShell>
  )
}

export default Manifesto
